### ISSUE TITLE
As a visitor I can create my account (create an account + personal information)

### ISSUE THREAD

**Issue by syksteaz** [amimouni/hawaiproject#2]

**Comment by syksteaz** [comment]
Done, sauf que la conséquence est que le facebook connect ne fonctionne pas. 
On redirige systématiquement vers la page edit du user profile, mais on peut mettre une page show si vous pensez que c'est utile.

**Comment by sergio-2015** [comment]
difficile de voir sans connaitre le sujet. fait ce qui te semble le + cool pr l'utilisateur
